// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'leads_distribution.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_LeadsDistribution _$$_LeadsDistributionFromJson(Map<String, dynamic> json) =>
    _$_LeadsDistribution(
      id: json['id'] as String?,
      recommendedBusinessUnit: json['recommendedBusinessUnit'] as String?,
      branchId: json['branchId'] as String?,
      branchName: json['branchName'] as String?,
      area: json['area'] as String?,
      posId: json['posId'] as String?,
      posName: json['posName'] as String?,
      custNo: json['custNo'] as String?,
      custMainNo: json['custMainNo'] as String?,
      memberId: json['memberId'] as String?,
      noFifgroupCard: json['noFifgroupCard'] as String?,
      lastBusinessUnit: json['lastBusinessUnit'] as String?,
      noPol: json['noPol'] as String?,
      vehicleType: json['vehicleType'] as String?,
      vehicleYear: json['vehicleYear'] as String?,
      bpkbName: json['bpkbName'] as String?,
      mobileNoOne: json['mobileNoOne'] as String?,
      mobileNoTwo: json['mobileNoTwo'] as String?,
      collectmobileNoOne: json['collectmobileNoOne'] as String?,
      collectmobileNoTwo: json['collectmobileNoTwo'] as String?,
      fixedPhoneArea: json['fixedPhoneArea'] as String?,
      fixedPhone: json['fixedPhone'] as String?,
      officePhoneArea: json['officePhoneArea'] as String?,
      officePhone: json['officePhone'] as String?,
      custName: json['custName'] as String?,
      birthDate: json['birthDate'] as int?,
      birthPlace: json['birthPlace'] as String?,
      job: json['job'] as String?,
      subOccupation: json['subOccupation'] as String?,
      address: json['address'] as String?,
      rtRw: json['rtRw'] as String?,
      province: json['province'] as String?,
      city: json['city'] as String?,
      kecamatan: json['kecamatan'] as String?,
      kelurahan: json['kelurahan'] as String?,
      zipCode: json['zipCode'] as String?,
      subZipCode: json['subZipCode'] as String?,
      visitDate: json['visitDate'] as int?,
      dataSource: json['dataSource'] as String?,
      flag: json['flag'] as String?,
      platform: json['platform'] as String?,
      gender: json['gender'] as String?,
      contractNumber: json['contractNumber'] as String?,
      priority: json['priority'] as String?,
      statusLeadId: json['statusLeadId'] as int?,
      getVehicleYear: json['getVehicleYear'] as String?,
      nik: json['nik'] as String?,
      remarkUh: json['remarkUh'] as String?,
      hasilFuUh: json['hasilFuUh'] as String?,
      hasilFu: json['hasilFu'] as String?,
      dataSourceName: json['dataSourceName'] as String?,
      vehicleDesc: json['vehicleDesc'] as String?,
      enhLeadId: json['enhLeadId'] as int?,
      startDate: json['startDate'] as int?,
      finalDate: json['finalDate'] as int?,
      colorFinal: json['colorFinal'] as String?,
      statusFgc: json['statusFgc'] as String?,
      plafondFgc: json['plafondFgc'] as String?,
    );

Map<String, dynamic> _$$_LeadsDistributionToJson(
        _$_LeadsDistribution instance) =>
    <String, dynamic>{
      'id': instance.id,
      'recommendedBusinessUnit': instance.recommendedBusinessUnit,
      'branchId': instance.branchId,
      'branchName': instance.branchName,
      'area': instance.area,
      'posId': instance.posId,
      'posName': instance.posName,
      'custNo': instance.custNo,
      'custMainNo': instance.custMainNo,
      'memberId': instance.memberId,
      'noFifgroupCard': instance.noFifgroupCard,
      'lastBusinessUnit': instance.lastBusinessUnit,
      'noPol': instance.noPol,
      'vehicleType': instance.vehicleType,
      'vehicleYear': instance.vehicleYear,
      'bpkbName': instance.bpkbName,
      'mobileNoOne': instance.mobileNoOne,
      'mobileNoTwo': instance.mobileNoTwo,
      'collectmobileNoOne': instance.collectmobileNoOne,
      'collectmobileNoTwo': instance.collectmobileNoTwo,
      'fixedPhoneArea': instance.fixedPhoneArea,
      'fixedPhone': instance.fixedPhone,
      'officePhoneArea': instance.officePhoneArea,
      'officePhone': instance.officePhone,
      'custName': instance.custName,
      'birthDate': instance.birthDate,
      'birthPlace': instance.birthPlace,
      'job': instance.job,
      'subOccupation': instance.subOccupation,
      'address': instance.address,
      'rtRw': instance.rtRw,
      'province': instance.province,
      'city': instance.city,
      'kecamatan': instance.kecamatan,
      'kelurahan': instance.kelurahan,
      'zipCode': instance.zipCode,
      'subZipCode': instance.subZipCode,
      'visitDate': instance.visitDate,
      'dataSource': instance.dataSource,
      'flag': instance.flag,
      'platform': instance.platform,
      'gender': instance.gender,
      'contractNumber': instance.contractNumber,
      'priority': instance.priority,
      'statusLeadId': instance.statusLeadId,
      'getVehicleYear': instance.getVehicleYear,
      'nik': instance.nik,
      'remarkUh': instance.remarkUh,
      'hasilFuUh': instance.hasilFuUh,
      'hasilFu': instance.hasilFu,
      'dataSourceName': instance.dataSourceName,
      'vehicleDesc': instance.vehicleDesc,
      'enhLeadId': instance.enhLeadId,
      'startDate': instance.startDate,
      'finalDate': instance.finalDate,
      'colorFinal': instance.colorFinal,
      'statusFgc': instance.statusFgc,
      'plafondFgc': instance.plafondFgc,
    };
